version: '3'

services:
  db:
    container_name: '${APP_NAME}-db'
    image: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
